#!/usr/bin/env python

import PySimpleGUI27 as sg
import json
import sys
import linuxcnc
import hal
import threading
from transitions import Machine, State
from os.path import expanduser

# Constants

STATE_WAITING = "STATE_WAITING"
STATE_IDLE = "STATE_IDLE"
STATE_LOAD_INIT = "STATE_LOAD_INIT"
STATE_LOAD_MOVE_LOADING = "STATE_LOAD_MOVE_LOADING"
STATE_LOAD_AT_LOADING = "STATE_LOAD_AT_LOADING"
STATE_LOAD_PROBE = "STATE_LOAD_PROBE"
STATE_LOAD_RETRACT = "STATE_LOAD_RETRACT"
STATE_UNLOAD_INIT = "STATE_UNLOAD_INIT"
STATE_UNLOAD_MOVE_LOADING = "STATE_UNLOAD_MOVE_LOADING"
STATE_UNLOAD_AT_LOADING = "STATE_UNLOAD_AT_LOADING"
STATE_UNLOAD_MOVE_SAFE = "STATE_UNLOAD_MOVE_SAFE"
STATE_UNLOAD_FLUSH = "STATE_UNLOAD_FLUSH"
STATE_ATC_INIT = "STATE_ATC_INIT"
STATE_RETURN_MOVE_SAFE_INITIAL = "STATE_RETURN_MOVE_SAFE_INITIAL"
STATE_RETURN_MOVE_CLEARANCE = "STATE_RETURN_MOVE_CLEARANCE"
STATE_RETURN_MOVE_CLOSE = "STATE_RETURN_MOVE_CLOSE"
STATE_RETURN_MOVE_POCKET = "STATE_RETURN_MOVE_POCKET"
STATE_RETURN_LOITER_POCKET = "STATE_RETURN_LOITER_POCKET"
STATE_RETURN_MOVE_SIDE = "STATE_RETURN_MOVE_SIDE"
STATE_RETURN_MOVE_SAFE_FINAL = "STATE_RETURN_MOVE_SAFE_FINAL"
STATE_RETURN_FINAL = "STATE_RETURN_FINAL"
STATE_RETRIEVE_MOVE_SAFE_INITIAL = "STATE_RETRIEVE_MOVE_SAFE_INITIAL"
STATE_RETRIEVE_FLUSH = "STATE_RETRIEVE_FLUSH"
STATE_RETRIEVE_MOVE_SIDE = "STATE_RETRIEVE_MOVE_SIDE"
STATE_RETRIEVE_MOVE_POCKET = "STATE_RETRIEVE_MOVE_POCKET"
STATE_RETRIEVE_LOITER_POCKET = "STATE_RETRIEVE_LOITER_POCKET"
STATE_RETRIEVE_MOVE_CLOSE = "STATE_RETRIEVE_MOVE_CLOSE"
STATE_RETRIEVE_MOVE_CLEARANCE = "STATE_RETRIEVE_MOVE_CLEARANCE"
STATE_RETRIEVE_MOVE_SAFE_FINAL = "STATE_RETRIEVE_MOVE_SAFE_FINAL"
STATE_RETRIEVE_FINAL = "STATE_RETRIEVE_FINAL"

EVENT_NOT_READY= "EVENT_NOT_READY"
EVENT_READY = "EVENT_READY"
EVENT_REQUEST_LOAD = "EVENT_REQUEST_LOAD"
EVENT_REQUEST_UNLOAD = "EVENT_REQUEST_UNLOAD"
EVENT_REQUEST_ATC = "EVENT_REQUEST_ATC"
EVENT_REQUEST_CONTINUE = "EVENT_REQUEST_CONTINUE"
EVENT_NEEDS_RETURN = "EVENT_NEEDS_RETURN"
EVENT_NEEDS_RETRIEVE = "EVENT_NEEDS_RETRIEVE"
EVENT_LOAD_OK = "EVENT_LOAD_OK"
EVENT_UNLOAD_OK = "EVENT_UNLOAD_OK"
EVENT_RETRIEVE_OK = "EVENT_RETRIEVE_OK"
EVENT_IN_POSITION = "EVENT_IN_POSITION"
EVENT_PROBE_TOUCHED = "EVENT_PROBE_TOUCHED"
EVENT_LOITER_COMPLETE = "EVENT_LOITER_COMPLETE"
EVENT_FLUSH_COMPLETE = "EVENT_FLUSH_COMPLETE"
EVENT_CONTINUE_ATC = "EVENT_CONTINUE_ATC"
EVENT_CONTINUE_UNLOAD = "EVENT_CONTINUE_UNLOAD"
EVENT_CONTINUE_LOAD = "EVENT_CONTINUE_LOAD"

def panic():
    """Panic by logging fatal error and exiting"""
    print "hal_fixed_atc_probe encountered a fatal error. Stopping."
    sys.exit(1)

# Config
config = None
try:
    with open(expanduser('~/hal_fixed_atc_probe_config.json')) as config_file:
        config = json.load(config_file)
except Exception as ex:
    print "Couldn't find config file at ~/hal_fixed_atc_probe_config.json"
    sys.exit(1)

def merge_coords(coords):
    """Merge and validate coordinate dicts from config"""
    base = {}
    for coord in coords:
        base.update(coord)
    # Validate
    if not (getattr(base, 'x', None) and getattr(base, 'y', None) and getattr(base, 'z', None)):
        raise AttributeError
    return base

def add_coords(a_coord, b_coord):
    """Perform a + b on coordinates, where a is fully-formed"""
    return {
        "x": a_coord.x + getattr(b_coord, 'x', 0),
        "y": a_coord.y + getattr(b_coord, 'y', 0),
        "z": a_coord.z + getattr(b_coord, 'z', 0)
    }

def get_pocket_coord(number, coord_type):
    """Get {x,y,z} coordinate tuple for a given pocket and coordinate type"""
    pocket = config.pockets[str(number)]
    if not pocket:
        raise ValueError

    base = merge_coords([config.pocket_default, pocket])

    if coord_type == 'pocket':
        return base
    if coord_type == 'side':
        return add_coords(base, config.pocket_side_offset)
    if coord_type == 'above-close':
        return add_coords(base, {'z': config.pocket_above_close_offset_z})
    if coord_type == 'above-clearance':
        return add_coords(base, {'z': config.pocket_above_clearance_offset_z})
    raise ValueError

class StateMachine(object):
    """Finite state machine for ATC and probe"""

    states = [
        State(STATE_WAITING, on_enter=['reset'], on_exit=None),
        State(STATE_IDLE, on_enter=['reset'], on_exit=None),

        State(STATE_LOAD_INIT, on_enter=['decide_load'], on_exit=None),
        State(STATE_LOAD_MOVE_LOADING, on_enter=['move_loading'], on_exit=None),
        State(STATE_LOAD_AT_LOADING, on_enter=None, on_exit=None), # TODO GUI "Continue"
        State(STATE_LOAD_PROBE, on_enter=['probe'], on_exit=None),
        State(STATE_LOAD_RETRACT, on_enter=['move_retract'], on_exit=None),

        State(STATE_UNLOAD_INIT, on_enter=['decide_unload'], on_exit=None),
        State(STATE_UNLOAD_MOVE_LOADING, on_enter=['move_loading'], on_exit=None),
        State(STATE_UNLOAD_AT_LOADING, on_enter=None, on_exit=None), # noop
        State(STATE_UNLOAD_MOVE_SAFE, on_enter=['move_safe'], on_exit=None),
        State(STATE_UNLOAD_FLUSH, on_enter=['flush_chuck'], on_exit=None),

        State(STATE_ATC_INIT, on_enter=['decide_atc'], on_exit=None),

        State(STATE_RETURN_MOVE_SAFE_INITIAL, on_enter=['move_safe'], on_exit=None),
        State(STATE_RETURN_MOVE_SIDE, on_enter=['move_pocket_side'], on_exit=None),
        State(STATE_RETURN_MOVE_POCKET, on_enter=['move_pocket'], on_exit=None),
        State(STATE_RETURN_LOITER_POCKET, on_enter=['open_chuck', 'loiter'], on_exit=None),
        State(STATE_RETURN_MOVE_CLOSE, on_enter=['move_pocket_above_close'], on_exit=None),
        State(STATE_RETURN_MOVE_CLEARANCE, on_enter=['close_chuck', 'move_pocket_above_clearance'], on_exit=None),
        State(STATE_RETURN_MOVE_SAFE_FINAL, on_enter=['move_safe'], on_exit=None),
        State(STATE_RETURN_FINAL, on_enter=['decide_after_return'], on_exit=None),

        State(STATE_RETRIEVE_MOVE_SAFE_INITIAL, on_enter=['move_safe'], on_exit=None),
        State(STATE_RETRIEVE_FLUSH, on_enter=['flush_chuck'], on_exit=None),
        State(STATE_RETRIEVE_MOVE_CLEARANCE, on_enter=['move_pocket_clearance'], on_exit=None),
        State(STATE_RETRIEVE_MOVE_CLOSE, on_enter=['move_pocket_close'], on_exit=None),
        State(STATE_RETRIEVE_MOVE_POCKET, on_enter=['open_chuck', 'move_pocket'], on_exit=None),
        State(STATE_RETRIEVE_LOITER_POCKET, on_enter=['loiter'], on_exit=None),
        State(STATE_RETRIEVE_MOVE_SIDE, on_enter=['close_chuck', 'move_pocket_side'], on_exit=None),
        State(STATE_RETRIEVE_MOVE_SAFE_FINAL, on_enter=['move_safe'], on_exit=None),
        State(STATE_RETRIEVE_FINAL, on_enter=['decide_after_retrieve'], on_exit=None)
    ]

    current_tool_number = -1 # Derived from linuxcnc status TODO what is "no tool"?
    is_changing_tool = None # None (not currently executing tool change) or integer (tool number)
    # TODO actual tool in spindle
    tool_table = () # Derived from linuxcnc status
    is_ok_for_mdi = False # Derived from linuxcnc status
    is_touching = False # Pin input
    is_chuck_open = False # Pin output
    is_changed = False # Pin output

    transitions = [
        # The state machine should "restart" to STATE_WAITING if MDI becomes unavailable.
        {'trigger': EVENT_NOT_READY, 'source': '*', 'dest': STATE_WAITING},
        # When MDI is ready, go to STATE_IDLE.
        {'trigger': EVENT_READY, 'source': STATE_WAITING, 'dest': STATE_IDLE},

        # Load and Probe
        {'trigger': EVENT_REQUEST_LOAD, 'source': STATE_IDLE, 'dest': STATE_LOAD_INIT},
        {'trigger': EVENT_NEEDS_RETURN, 'source': STATE_LOAD_INIT, 'dest': STATE_RETURN_MOVE_SAFE},
        {'trigger': EVENT_NEEDS_RETRIEVE, 'source': STATE_LOAD_INIT, 'dest': STATE_RETRIEVE_MOVE_SAFE_INITIAL},
        {'trigger': EVENT_LOAD_OK, 'source': STATE_LOAD_INIT, 'dest': STATE_LOAD_MOVE_LOADING},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_LOAD_MOVE_LOADING, 'dest': STATE_LOAD_AT_LOADING},
        {'trigger': EVENT_REQUEST_CONTINUE, 'source': STATE_LOAD_AT_LOADING, 'dest': STATE_LOAD_PROBE},
        {'trigger': EVENT_PROBE_TOUCHED, 'source': STATE_LOAD_PROBE, 'dest': STATE_LOAD_RETRACT},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_LOAD_RETRACT, 'dest': STATE_RETURN_MOVE_SAFE_INITIAL},

        # Unload
        {'trigger': EVENT_REQUEST_UNLOAD, 'source': STATE_IDLE, 'dest': STATE_UNLOAD_INIT},
        {'trigger': EVENT_NEEDS_RETURN, 'source': STATE_UNLOAD_INIT, 'dest': STATE_RETURN_MOVE_SAFE},
        {'trigger': EVENT_NEEDS_RETRIEVE, 'source': STATE_UNLOAD_INIT, 'dest': STATE_RETRIEVE_MOVE_SAFE_INITIAL},
        {'trigger': EVENT_UNLOAD_OK, 'source': STATE_UNLOAD_INIT, 'dest': STATE_UNLOAD_MOVE_LOADING},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_UNLOAD_MOVE_LOADING, 'dest': STATE_UNLOAD_AT_LOADING},
        {'trigger': EVENT_REQUEST_CONTINUE, 'source': STATE_UNLOAD_AT_LOADING, 'dest': STATE_UNLOAD_MOVE_SAFE},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_UNLOAD_MOVE_SAFE, 'dest': STATE_UNLOAD_FLUSH},
        {'trigger': EVENT_FLUSH_COMPLETE, 'source': STATE_UNLOAD_FLUSH, 'dest': STATE_IDLE},

        # General ATC
        {'trigger': EVENT_REQUEST_ATC, 'source': STATE_IDLE, 'dest': STATE_ATC_INIT},

        # ATC Return
        {'trigger': EVENT_NEEDS_RETURN, 'source': STATE_ATC_INIT, 'dest': STATE_RETURN_MOVE_SAFE},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETURN_MOVE_SAFE, 'dest': STATE_RETURN_MOVE_CLEARANCE},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETURN_MOVE_CLEARANCE, 'dest': STATE_RETURN_MOVE_CLOSE},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETURN_MOVE_CLOSE, 'dest': STATE_RETURN_MOVE_POCKET},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETURN_MOVE_POCKET, 'dest': STATE_RETURN_LOITER_POCKET},
        {'trigger': EVENT_LOITER_COMPLETE, 'source': STATE_RETURN_LOITER_POCKET, 'dest': STATE_RETURN_MOVE_SIDE},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETURN_MOVE_SIDE, 'dest': STATE_RETURN_FINAL},
        {'trigger': EVENT_CONTINUE_ATC, 'source': STATE_RETURN_FINAL, 'dest': STATE_RETRIEVE_MOVE_SAFE_INITIAL},
        {'trigger': EVENT_LOAD_COMPLETE, 'source': STATE_RETURN_FINAL, 'dest': STATE_IDLE},
        {'trigger': EVENT_CONTINUE_UNLOAD, 'source': STATE_RETURN_FINAL, 'dest': STATE_UNLOAD_INIT},
        {'trigger': EVENT_CONTINUE_LOAD, 'source': STATE_RETURN_FINAL, 'dest': STATE_LOAD_INIT},

        # ATC Retrieval
        {'trigger': EVENT_RETRIEVE_OK, 'source': STATE_ATC_INIT, 'dest': STATE_RETRIEVE_MOVE_SAFE_INITIAL},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETRIEVE_MOVE_SAFE_INITIAL, 'dest': STATE_RETRIEVE_FLUSH},
        {'trigger': EVENT_FLUSH_COMPLETE, 'source': STATE_RETRIEVE_FLUSH, 'dest': STATE_RETRIEVE_MOVE_SIDE},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETRIEVE_MOVE_SIDE, 'dest': STATE_RETRIEVE_MOVE_POCKET},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETRIEVE_MOVE_POCKET, 'dest': STATE_RETRIEVE_LOITER_POCKET},
        {'trigger': EVENT_LOITER_COMPLETE, 'source': STATE_RETRIEVE_LOITER_POCKET, 'dest': STATE_RETRIEVE_MOVE_CLOSE},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETRIEVE_MOVE_CLOSE, 'dest': STATE_RETRIEVE_MOVE_CLEARANCE},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETRIEVE_MOVE_CLEARANCE, 'dest': STATE_RETRIEVE_MOVE_SAFE_FINAL},
        {'trigger': EVENT_IN_POSITION, 'source': STATE_RETRIEVE_MOVE_SAFE_FINAL, 'dest': STATE_RETRIEVE_FINAL},
        {'trigger': EVENT_ATC_COMPLETE, 'source': STATE_RETRIEVE_FINAL, 'dest': STATE_IDLE},
        {'trigger': EVENT_CONTINUE_UNLOAD, 'source': STATE_RETRIEVE_FINAL, 'dest': STATE_UNLOAD_INIT},
        {'trigger': EVENT_CONTINUE_LOAD, 'source': STATE_RETRIEVE_FINAL, 'dest': STATE_LOAD_INIT},
    ]

    def __init__(self):
        """Initialize the state machine"""
        self.machine = Machine(
            model=self,
            queued=True,
            states=StateMachine.states,
            transitions=StateMachine.transitions,
            initial=StateStartup
        )

    def reset(self):
        # TODO more...
        # Ensure chuck is closed
        self.close_chuck()

    def decide_load(self):
        # TODO clauses
        if True:
            self.machine.dispatch(EVENT_LOAD_OK)
        elif True:
            self.machine.dispatch(EVENT_NEEDS_RETRIEVE)
        else:
            self.machine.dispatch(EVENT_NEEDS_RETURN)

    def decide_unload(self):
        # TODO clauses
        if True:
            self.machine.dispatch(EVENT_UNLOAD_OK)
        elif True:
            self.machine.dispatch(EVENT_NEEDS_RETRIEVE)
        else:
            self.machine.dispatch(EVENT_NEEDS_RETURN)

    def decide_atc(self):
        # TODO clause
        if True:
            self.machine.dispatch(EVENT_RETRIEVE_OK)
        else:
            self.machine.dispatch(EVENT_NEEDS_RETURN)

    def decide_after_return(self):
        # TODO clauses
        if True:
            self.machine.dispatch(EVENT_CONTINUE_ATC)
        elif True:
            self.machine.dispatch(EVENT_LOAD_COMPLETE)
        elif True:
            self.machine.dispatch(EVENT_CONTINUE_LOAD)
        else:
            self.machine.dispatch(EVENT_CONTINUE_UNLOAD)

    def decide_after_retrieve(self):
        # TODO clauses
        if True:
            self.machine.dispatch(EVENT_ATC_COMPLETE)
        elif True:
            self.machine.dispatch(EVENT_CONTINUE_LOAD)
        else:
            self.machine.dispatch(EVENT_CONTINUE_UNLOAD)

    def request_load_tool(self, tool):
        pass # TODO

    def request_unload_tool(self, tool):
        pass # TODO

    def set_tool_change(self, is_tool_change, number, changed):
        # Derive
        is_changing_tool = None
        if is_tool_change and number and not changed:
            is_changing_tool = number

        # If changed...
        if is_changing_tool != self.is_changing_tool:
            self.is_changing_tool = is_changing_tool
            if self.is_changing_tool:
                self.machine.dispatch(EVENT_REQUEST_ATC)
            else:
                pass
                # TODO ? Could possibly dispatch a end-of-atc type of event

    def set_is_touching(self, is_touching):
        if is_touching != self.is_touching:
            self.is_touching = is_touching
            if self.is_touching:
                self.machine.dispatch(EVENT_PROBE_TOUCHED)

    def set_current_tool_number(self, tool):
        self.current_tool_number = tool

    def set_tool_table(self, tool_table):
        self.tool_table = tool_table

    def set_is_ok_for_mdi(self, is_ok_for_mdi):
        # If changed...
        if is_ok_for_mdi != self.is_ok_for_mdi:
            self.is_ok_for_mdi = is_ok_for_mdi
            # Dispatch appropriate event
            if self.is_ok_for_mdi:
                self.machine.dispatch(EVENT_READY)
            else:
                self.machine.dispatch(EVENT_NOT_READY)
                panic()

    def open_chuck(self):
        self.is_chuck_open = True

    def close_chuck(self):
        self.is_chuck_open = False

    def flush_chuck(self):
        """Open chuck and dispatch EVENT_FLUSH_COMPLETE after config.loiter_seconds"""
        self.open_chuck()
        def chuck_timer_cb():
            self.close_chuck()
            self.machine.dispatch(EVENT_FLUSH_COMPLETE)
        timer = threading.Timer(config.flush_seconds, chuck_timer_cb)
        timer.start()

    def loiter(self):
        """Dispatch EVENT_LOITER_COMPLETE after config.loiter_seconds"""
        def loiter_timer_cb():
            self.machine.dispatch(EVENT_LOITER_COMPLETE)
        timer = threading.Timer(config.loiter_seconds, loiter_timer_cb)
        timer.start()

    def move_coord_absolute(self, coord, feed=3600, dispatch_in_position=True):
        send_gcode("G21 G53 G0 F{} X{} Y{} Z{}".format(feed, coord.x, coord.y, coord.z))
        if dispatch_in_position:
            self.machine.dispatch(EVENT_IN_POSITION)

    def move_coord_relative(self, coord, feed=3600, dispatch_in_position=True):
        send_gcode("G21 G91 G0 F{} X{} Y{} Z{}".format(feed, coord.x, coord.y, coord.z))
        if dispatch_in_position:
            self.machine.dispatch(EVENT_IN_POSITION)

    def move_loading(self):
        # TODO avoid tool rack boundary
        self.move_coord_absolute(config.loading)

    def probe(self):
        pass # TODO probe/check loop

    def move_retract(self):
        coord = {"x": 0, "y": 0, "z": config.probe_retract_offset_z}
        self.move_coord_relative(coord)

    def move_safe(self):
        # TODO avoid tool rack boundary
        self.move_coord_absolute(config.safe)

    def move_pocket_side(self):
        coord = get_pocket_coord(self.is_changing_tool, 'side')
        self.move_coord_absolute(coord)

    def move_pocket(self):
        coord = get_pocket_coord(self.is_changing_tool, 'pocket')
        self.move_coord_absolute(coord)

    def move_pocket_above_close(self):
        coord = get_pocket_coord(self.is_changing_tool, 'above-close')
        self.move_coord_absolute(coord)

    def move_pocket_above_clearance(self):
        # TODO avoid tool rack boundary (when returning)
        coord = get_pocket_coord(self.is_changing_tool, 'above-clearance')
        self.move_coord_absolute(coord)

# Configure HAL Component
h = hal.component("hal_fixed_atc_probe")
# IN:
h.newpin("number", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("tool_prepare", hal.HAL_BIT, hal.HAL_IN)  # looped to `prepared`
h.newpin("tool_change", hal.HAL_BIT, hal.HAL_IN)
h.newpin("probe", hal.HAL_BIT, hal.HAL_IN)
# OUT:
h.newpin("prepared", hal.HAL_BIT, hal.HAL_OUT)  # looped to `tool_prepare`
h.newpin("changed", hal.HAL_BIT, hal.HAL_OUT)
h.newpin("chuck", hal.HAL_BIT, hal.HAL_OUT)
h.ready()

# Configure GUI window
layout = [[sg.Text('Tool # = Pocket #')],
          [sg.Text('Load/Probe Tool #'), sg.InputText(key='InputLoad',
                                                      size=(3, 1), do_not_clear=False), sg.Button('Load')],
          [sg.Text('Unload Tool #'), sg.InputText(key='InputUnload',
                                                  size=(3, 1), do_not_clear=False), sg.Button('Unload')],
          # output for stdout/stderr
          [sg.Output(size=(50, 10))]]
window = sg.Window('Tool Changer and Probe', layout).Finalize()

def send_gcode(gcode):
    """G-code sender"""
    c = linuxcnc.command()
    c.mode(linuxcnc.MODE_MDI)
    c.wait_complete()
    # TODO does this block? if yes, remove wait_complete below. if no, increase wait time
    c.mdi(gcode)
    c.wait_complete()

def status_routine(state, status):
    """Status routine (for main loop)"""

    # Poll status channel
    try:
        status.poll()
    except linuxcnc.error as ex:
        print ex
        panic()

    # Read status into state
    state.set_current_tool_number(status.tool_in_spindle)  # integer
    state.set_tool_table(status.tool_table)  # array
    state.set_is_ok_for_mdi(not status.estop and status.enabled and status.homed and (
        status.interp_state == linuxcnc.INTERP_IDLE))
    # state.set_task_mode(status.task_mode) # mdi, auto, manual
    # state.set_is_in_position(status.inpos != 0)
    # state.set_spindle_enabled(status.spindle_enabled)
    # state.set_spindle_speed(status.spindle_speed)
    # state.set_file(status.file)

def hal_routine(state):
    """HAL routine (for main loop)"""

    # input pins
    state.set_tool_change(h.tool_change == 1, h.number, h.changed == 1)
    state.set_is_touching(h.probe == 1)
    # ouput pins
    h.chuck = 1 if state.is_chuck_open else 0
    h.changed = 1 if state.is_changed else 0
    # loop `prepared` to `tool_prepare`
    h.prepared = h.tool_prepare

def gui_routine(state):
    """GUI routine (for main loop)"""

    event, values = window.Read(timeout=10)
    i = None
    if event == 'Load':
        try:
            i = int(values['InputLoad'])
        except ValueError:
            print 'Bad input'

        if i is not None and i >= 0:
            state.request_load_tool(i)
    elif event == 'Unload':
        try:
            i = int(values['InputUnload'])
        except ValueError:
            print 'Bad input'

        if i is not None and i >= 0:
            state.request_unload_tool(i)

# Initialize state machine
state = StateMachine()

# Create connection to LinuxCNC status channel
status = linuxcnc.stat()

# Main loop
while True:
    status_routine(state, status)
    hal_routine(state)
    gui_routine(state)
